# Generated by Django 3.2.5 on 2021-07-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('icon', models.ImageField(null=True, upload_to='icons/')),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
