# Generated by Django 3.2.5 on 2021-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='intranet/static/videos/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='icon',
            field=models.ImageField(null=True, upload_to='intranet/static/icons/'),
        ),
    ]
