# Generated by Django 3.2.5 on 2021-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20210716_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='materials',
            field=models.FileField(null=True, upload_to='intranet/static/materials'),
        ),
    ]
