# Generated by Django 3.2.5 on 2021-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('Dis', models.TextField(max_length=1000, verbose_name='Описание')),
                ('file', models.FileField(upload_to='media/', verbose_name='Видео')),
            ],
        ),
    ]
