# Generated by Django 3.2.5 on 2021-07-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostervid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('price', models.IntegerField(verbose_name='Цена курса')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostervid.video')),
            ],
        ),
    ]
